version: '2'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=/rails_vue_activestrage_sandbox
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_URL: 'mysql2://root:test123@db:3306'
    command: bundle exec puma --config config/puma.rb
    volumes:
      - .:/rails_vue_activestrage_sandbox
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.6
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: test123
    ports:
     - "3307:3306"
